# Generated by Django 3.1.2 on 2020-11-05 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voyage_prevu', '0034_auto_20201105_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAvion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_depart', models.CharField(choices=[('MAM', 'Mamoudzou'), ('MO', 'Moroni'), ('FOU', 'Foumbouni'), ('AJ', 'Anjouan')], max_length=50)),
                ('ville_destination', models.CharField(choices=[('MAM', 'Mamoudzou'), ('MO', 'Moroni'), ('FOU', 'Foumbouni'), ('AJ', 'Anjouan')], max_length=50)),
                ('date_depart', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelBateau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_depart', models.CharField(choices=[('MAM', 'Mamoudzou'), ('MO', 'Moroni'), ('FOU', 'Foumbouni'), ('AJ', 'Anjouan')], max_length=50)),
                ('ville_destination', models.CharField(choices=[('MAM', 'Mamoudzou'), ('MO', 'Moroni'), ('FOU', 'Foumbouni'), ('AJ', 'Anjouan')], max_length=50)),
                ('date_depart', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateTimeField()),
                ('ile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyage_prevu.ile')),
                ('ville_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyage_prevu.ville')),
                ('ville_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vile_destination', to='voyage_prevu.ville')),
            ],
        ),
    ]
