# Generated by Django 3.1.7 on 2021-03-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=50, verbose_name='Téléphone portable')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Adresse email')),
                ('sujet', models.TextField(verbose_name='Titre du message')),
                ('message', models.TextField(verbose_name='Message complet')),
                ('dateAjout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'integration")),
            ],
            options={
                'verbose_name': 'Message',
            },
        ),
    ]
