# Generated by Django 3.1.7 on 2021-03-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, editable=False, max_length=255, null=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(editable=False, verbose_name='Message complet'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nom',
            field=models.CharField(editable=False, max_length=50, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sujet',
            field=models.TextField(editable=False, verbose_name='Titre du message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(editable=False, max_length=50, verbose_name='Téléphone portable'),
        ),
    ]
