# Generated by Django 3.1.2 on 2020-11-06 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0035_aeroport_port'),
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbus',
            name='typev',
            field=models.CharField(default='BU', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelavion',
            name='ville_depart',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='Vile_desnation', to='voyage_prevu.aeroport'),
        ),
        migrations.AlterField(
            model_name='modelavion',
            name='ville_destination',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='Vile_dstination', to='voyage_prevu.aeroport'),
        ),
        migrations.AlterField(
            model_name='modelbateau',
            name='ville_depart',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='Vile_destinaion', to='voyage_prevu.port'),
        ),
        migrations.AlterField(
            model_name='modelbateau',
            name='ville_destination',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='Vile_destinatin', to='voyage_prevu.aeroport'),
        ),
    ]
