# Generated by Django 3.1.2 on 2020-11-06 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0035_aeroport_port'),
        ('accueil', '0002_auto_20201106_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelbus',
            name='ile',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='voyage_prevu.ile'),
        ),
        migrations.AlterField(
            model_name='modelbus',
            name='ville_depart',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='voyage_prevu.ville'),
        ),
    ]
