# Generated by Django 3.1.7 on 2021-03-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0002_auto_20210306_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Message complet'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sujet',
            field=models.TextField(verbose_name='Titre du message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(max_length=50, verbose_name='Téléphone portable'),
        ),
    ]
