# Generated by Django 3.1.2 on 2020-11-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0037_auto_20201106_2039'),
        ('accueil', '0003_auto_20201106_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelavion',
            name='typev',
            field=models.CharField(default='BU', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelbateau',
            name='typev',
            field=models.CharField(default='BA', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelbateau',
            name='ville_destination',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='Vile_destinatin', to='voyage_prevu.port'),
        ),
    ]
