# Generated by Django 3.1.2 on 2020-11-07 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0043_auto_20201107_0909'),
        ('accueil', '0004_auto_20201107_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelavion',
            name='ville_depart',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='Vile_desnation', to='voyage_prevu.ville'),
        ),
        migrations.AlterField(
            model_name='modelavion',
            name='ville_destination',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='Vile_dstination', to='voyage_prevu.ville'),
        ),
        migrations.AlterField(
            model_name='modelbateau',
            name='ville_depart',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='Vile_destinaion', to='voyage_prevu.ville'),
        ),
        migrations.AlterField(
            model_name='modelbateau',
            name='ville_destination',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='Vile_destinatin', to='voyage_prevu.ville'),
        ),
    ]
