# Generated by Django 3.1.2 on 2020-11-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0044_auto_20201107_1314'),
        ('accueil', '0005_auto_20201107_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recherche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typev', models.CharField(max_length=50)),
                ('date_depart', models.DateTimeField()),
                ('ville_depart', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='Vile_deation', to='voyage_prevu.ville')),
                ('ville_destination', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='Vile_dsation', to='voyage_prevu.ville')),
            ],
        ),
    ]
