"""
Django settings for vpp project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from qr_code.qrcode import constants
import os
from django.urls import reverse_lazy
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&@ehk(2d@$11&@6h3$doykzv(q-1%xh-5r=$zuv&k&&pgyhf*p'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True

ALLOWED_HOSTS = []

# Cacher les variables 
# CACHES={'default': django_cache_url.config()}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # paypal
    'paypal.standard.ipn',
    # Mes applications

    'qr_code',

    'voyages',
    'accueil',
    'utilisateur',
    'paiement',
    'achat',
    'agence',
    'banques',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STRIPE_PUBLISHABLE_KEY = 'pk_test_51HcnuxBXtR6NoHYCmhTktICwoW89a2ZBU5svHO8WjIFqJnlG9gsFPQFaYs0fosAV7a58Ks4O7JaSwXjJpDEdac1c00cCwNZHMf'
STRIPE_SECRET_KEY = 'sk_test_51HcnuxBXtR6NoHYCJUVZy9GS0kNVhQjWF9eqESoCtYdr2qhKTQgmv3xuTMdIoe2EqrKmnXqUfS8GIoh1Ko6ISJgC00An6P4iWL'

PAYPAL_TEST = True

# SMS_BACKEND = 'sms.backends.console.SmsBackend'
SMS_BACKEND = 'sms.backends.filebased.SmsBackend'
SMS_FILE_PATH = '/tmp/app-messages'

ROOT_URLCONF = 'vpp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vpp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

gettext = lambda x: x

LANGUAGES = (
   ('fr', gettext('French')),
   ('en', gettext('English')),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]


LOGIN_REDIRECT_URL = '/infos/dashbord'

# LOGOUT_REDIRECT_URL = '/infos/logout'

# https://docs.djangoproject.com/fr/3.1/ref/settings/


# Caches.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'qr-code': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'qr-code-cache',
        'TIMEOUT': 3600
    }
}

# site de docummentation de Qr code
# https://django-qr-code.readthedocs.io/en/latest/pages/README.html


# Django QR Code specific options.
QR_CODE_CACHE_ALIAS = 'qr-code'
QR_CODE_URL_PROTECTION = {
    # Optional random token length for URL protection. Defaults to 20.
    constants.TOKEN_LENGTH: 30,
    # Optional signing key for URL token. Uses SECRET_KEY if not defined.
    constants.SIGNING_KEY: 'C-Transport avec Zaenma',
    # Optional signing salt for URL token.
    constants.SIGNING_SALT: 'my-signing-salt',
    # Tells whether a registered user can request the QR code URLs from outside a site that uses this app. It can be a boolean value used for any user, or a callable that takes a user as parameter. Defaults to False (nobody can access the URL without the security token).
    constants.ALLOWS_EXTERNAL_REQUESTS_FOR_REGISTERED_USER: False
}


# projrts rapidSMS 

# https://rapidsms.readthedocs.io/en/develop/tutorial/
# https://github.com/rapidsms/rapidsms-project-template

# utilisation d'environnement virtuel
# https://docs.python.org/fr/3/tutorial/venv.html

# authentification 
# https://docs.djangoproject.com/fr/3.1/topics/auth/default/

# tutorial de paiement avec strip
# https://testdriven.io/blog/django-stripe-tutorial/