# Generated by Django 3.1.2 on 2020-11-03 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('ile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyage_prevu.ile')),
            ],
        ),
        migrations.RemoveField(
            model_name='lesville',
            name='ile',
        ),
        migrations.DeleteModel(
            name='TypeVoyage',
        ),
        migrations.AddField(
            model_name='voyagesprevu',
            name='codeVoyage',
            field=models.CharField(max_length=50, null=True, verbose_name='Code de voyage (Identifiant du Voyage)'),
        ),
        migrations.AddField(
            model_name='voyagesprevu',
            name='dateDepert',
            field=models.DateTimeField(null=True, verbose_name='Date de départ'),
        ),
        migrations.AddField(
            model_name='voyagesprevu',
            name='datearrivee',
            field=models.DateTimeField(null=True, verbose_name="Date d'arrivée à prevoir"),
        ),
        migrations.AddField(
            model_name='voyagesprevu',
            name='nombreSiege',
            field=models.IntegerField(null=True, verbose_name='Total de siège disponible'),
        ),
        migrations.AddField(
            model_name='voyagesprevu',
            name='prix',
            field=models.IntegerField(null=True, verbose_name='Prix par siège'),
        ),
        migrations.AddField(
            model_name='voyagesprevu',
            name='typeVoyage',
            field=models.CharField(choices=[('BATEAU', 'Bateau'), ('AVION', 'Avion'), ('BUS', 'Bus')], default='BUS', max_length=20, verbose_name='Moyen de transport'),
        ),
        migrations.DeleteModel(
            name='LesIle',
        ),
        migrations.DeleteModel(
            name='LesVille',
        ),
        migrations.AddField(
            model_name='voyagesprevu',
            name='villeArrivee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='supervisor_of', to='voyage_prevu.ville'),
        ),
        migrations.AddField(
            model_name='voyagesprevu',
            name='villeDepart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='voyage_prevu.ville'),
        ),
    ]
