# Generated by Django 3.1.2 on 2020-11-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0002_auto_20201103_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagesprevu',
            name='villeArrivee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='supervisor_of', to='voyage_prevu.ville', verbose_name='Ville de destination'),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='villeDepart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voyage_prevu.ville', verbose_name='Ville de départ'),
        ),
    ]
