# Generated by Django 3.1.2 on 2020-11-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0003_auto_20201103_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagesprevu',
            name='codeVoyage',
            field=models.CharField(max_length=50, verbose_name='Code de voyage (Identifiant du Voyage)'),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='dateDepert',
            field=models.DateTimeField(verbose_name='Date de départ'),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='datearrivee',
            field=models.DateTimeField(verbose_name="Date d'arrivée à prevoir"),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='nombreSiege',
            field=models.IntegerField(verbose_name='Total de siège disponible'),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='prix',
            field=models.IntegerField(verbose_name='Prix par siège'),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='villeArrivee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='supervisor_of', to='voyage_prevu.ville', verbose_name='Ville de destination'),
        ),
    ]
