# Generated by Django 3.1.2 on 2020-11-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0006_auto_20201103_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyagesprevu',
            name='villeEscale',
            field=models.ManyToManyField(related_name='Ville_escale', to='voyage_prevu.Ville', verbose_name="Villes d'sscale (si l'on prevoit)"),
        ),
    ]
