# Generated by Django 3.1.2 on 2020-11-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0007_voyagesprevu_villeescale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagesprevu',
            name='typeVoyage',
            field=models.CharField(choices=[('BA', 'Bateau'), ('AV', 'Avion'), ('BU', 'Bus')], default='BUS', max_length=20, verbose_name='Moyen de transport'),
        ),
    ]
