# Generated by Django 3.1.2 on 2020-11-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0006_auto_20201104_1358'),
        ('voyage_prevu', '0008_auto_20201104_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagesprevu',
            name='agencePrincipal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agence.agence', verbose_name='Agence Organisatrice du voyage'),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='villeArrivee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Ville_destination', to='voyage_prevu.ville', verbose_name='Ville de destination'),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='villeDepart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyage_prevu.ville', verbose_name='Ville de départ'),
        ),
    ]
