# Generated by Django 3.1.2 on 2020-11-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0011_auto_20201104_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyagesprevu',
            name='dateretour',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'arrivée à prevoir"),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='bagage',
            field=models.IntegerField(blank=True, verbose_name='Quantité de bagage autorisé'),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='datearrivee',
            field=models.DateTimeField(blank=True, verbose_name="Date d'arrivée à prevoir"),
        ),
        migrations.RemoveField(
            model_name='voyagesprevu',
            name='villeEscale',
        ),
        migrations.AddField(
            model_name='voyagesprevu',
            name='villeEscale',
            field=models.ManyToManyField(blank=True, related_name='Ville_escale', to='voyage_prevu.Ville', verbose_name="Villes d'sscale (si l'on prevoit)"),
        ),
    ]
