# Generated by Django 3.1.2 on 2020-11-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0012_auto_20201104_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagesprevu',
            name='bagage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantité de bagage autorisé'),
        ),
    ]
