# Generated by Django 3.1.2 on 2020-11-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0013_auto_20201104_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagesprevu',
            name='bagage',
            field=models.IntegerField(default=30, verbose_name='Quantité de bagage autorisé'),
        ),
    ]
