# Generated by Django 3.1.2 on 2020-11-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0014_auto_20201104_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyagesprevu',
            name='bagage',
        ),
    ]
