# Generated by Django 3.1.2 on 2020-11-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0015_remove_voyagesprevu_bagage'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyagesprevu',
            name='bagage',
            field=models.IntegerField(default=30, verbose_name='Quantité de bagage autorisé'),
        ),
    ]
