# Generated by Django 3.1.2 on 2020-11-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0017_auto_20201104_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyagesprevu',
            name='bagage',
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='nombreSiege',
            field=models.IntegerField(blank=True, verbose_name='Total de siège disponible'),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='typeVoyage',
            field=models.CharField(choices=[('BA', 'Bateau'), ('AV', 'Avion'), ('BU', 'Bus')], max_length=20, verbose_name='Moyen de transport'),
        ),
    ]
