# Generated by Django 3.1.2 on 2020-11-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0018_auto_20201104_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyagesprevu',
            name='bagage',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='Quantité de bagage autorisé'),
        ),
    ]
