# Generated by Django 3.1.2 on 2020-11-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0020_auto_20201104_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagesprevu',
            name='villeEscale',
            field=models.ManyToManyField(blank=True, related_name='Ville_escale', to='voyage_prevu.Ville', verbose_name="Villes d'sscale (si l'on prevoit)"),
        ),
    ]
