# Generated by Django 3.1.2 on 2020-11-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0021_auto_20201104_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyagesprevu',
            name='ile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voyage_prevu.ile', verbose_name="Ile : si c'est une voyage terrestre"),
        ),
    ]
