# Generated by Django 3.1.2 on 2020-11-04 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0022_voyagesprevu_ile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyagesprevu',
            name='villeEscale',
        ),
        migrations.AddField(
            model_name='voyagesprevu',
            name='villeEscale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Ville_escale', to='voyage_prevu.ville', verbose_name="Villes d'sscale (si l'on prevoit)"),
        ),
    ]
