# Generated by Django 3.1.2 on 2020-11-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0023_auto_20201104_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyagesprevu',
            name='villeEscale',
        ),
    ]
