# Generated by Django 3.1.2 on 2020-11-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0025_voyagesprevu_villeescale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagesprevu',
            name='bagage',
            field=models.IntegerField(default=30, null=True, verbose_name='Quantité de bagage autorisé'),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='datearrivee',
            field=models.DateTimeField(null=True, verbose_name="Date d'arrivée à prevoir"),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='dateretour',
            field=models.DateTimeField(null=True, verbose_name="Date d'arrivée à prevoir"),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='ile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voyage_prevu.ile', verbose_name="Ile : si c'est une voyage terrestre"),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='nombreSiege',
            field=models.IntegerField(null=True, verbose_name='Total de siège disponible'),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='villeEscale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Ville_escale', to='voyage_prevu.ville', verbose_name="Villes d'sscale (si l'on prevoit)"),
        ),
    ]
