# Generated by Django 3.1.2 on 2020-11-04 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0026_auto_20201104_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagesprevu',
            name='bagage',
            field=models.IntegerField(blank=True, verbose_name='Quantité de bagage autorisé'),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='datearrivee',
            field=models.DateTimeField(blank=True, verbose_name="Date d'arrivée à prevoir"),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='dateretour',
            field=models.DateTimeField(blank=True, verbose_name="Date d'arrivée à prevoir"),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='ile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='voyage_prevu.ile', verbose_name="Ile : si c'est une voyage terrestre"),
        ),
        migrations.AlterField(
            model_name='voyagesprevu',
            name='nombreSiege',
            field=models.IntegerField(blank=True, verbose_name='Total de siège disponible'),
        ),
        migrations.RemoveField(
            model_name='voyagesprevu',
            name='villeEscale',
        ),
        migrations.AddField(
            model_name='voyagesprevu',
            name='villeEscale',
            field=models.ManyToManyField(blank=True, related_name='Ville_escale', to='voyage_prevu.Ville', verbose_name="Villes d'sscale (si l'on prevoit)"),
        ),
    ]
