# Generated by Django 3.1.2 on 2020-11-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0027_auto_20201104_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voyagesprevu',
            old_name='villeEscale',
            new_name='ville_escale',
        ),
    ]
