# Generated by Django 3.1.2 on 2020-11-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0028_auto_20201104_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyagesprevu',
            name='ville_escale',
        ),
        migrations.AddField(
            model_name='voyagesprevu',
            name='villeEscale',
            field=models.ManyToManyField(blank=True, related_name='VilleEscale', to='voyage_prevu.Ville', verbose_name="Villes d'sscale (si l'on prevoit)"),
        ),
    ]
