# Generated by Django 3.1.2 on 2020-11-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0031_auto_20201104_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagesprevu',
            name='datearrivee',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'arrivée à prevoir"),
        ),
    ]
