# Generated by Django 3.1.2 on 2020-11-04 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0032_auto_20201104_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voyagesprevu',
            options={'verbose_name_plural': 'voyage_prevu'},
        ),
    ]
