# Generated by Django 3.1.2 on 2020-11-05 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0033_auto_20201104_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voyagesprevu',
            options={},
        ),
    ]
