# Generated by Django 3.1.2 on 2020-11-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0034_auto_20201105_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non', models.CharField(max_length=50, verbose_name='Les villes où se situent les aéroports')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non', models.CharField(max_length=50, verbose_name='Les villes où se situent les ports')),
            ],
        ),
    ]
