# Generated by Django 3.1.2 on 2020-11-06 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0035_aeroport_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeroport',
            name='non',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='nomaeroport', to='voyage_prevu.ville', verbose_name='Les villes où se situent les aéroports'),
        ),
        migrations.AlterField(
            model_name='port',
            name='non',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='nomport', to='voyage_prevu.ville', verbose_name='Les villes où se situent les ports'),
        ),
    ]
