# Generated by Django 3.1.2 on 2020-11-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0037_auto_20201106_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeroport',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Les villes où se situent les aéroports'),
        ),
        migrations.AlterField(
            model_name='port',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Les villes où se situent les ports'),
        ),
    ]
