# Generated by Django 3.1.2 on 2020-11-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0038_auto_20201107_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeroport',
            name='ile',
            field=models.ForeignKey(default='Anjouan', on_delete=django.db.models.deletion.CASCADE, to='voyage_prevu.ile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='port',
            name='ile',
            field=models.ForeignKey(default='Ngazidja', on_delete=django.db.models.deletion.CASCADE, to='voyage_prevu.ile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aeroport',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='port',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
