# Generated by Django 3.1.2 on 2020-11-07 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0039_auto_20201107_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeroport',
            name='ile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='voyage_prevu.ile'),
        ),
        migrations.AlterField(
            model_name='port',
            name='ile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voyage_prevu.ile'),
        ),
    ]
