# Generated by Django 3.1.2 on 2020-11-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0005_auto_20201107_1314'),
        ('voyage_prevu', '0043_auto_20201107_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='ile',
        ),
        migrations.RemoveField(
            model_name='port',
            name='nom',
        ),
        migrations.DeleteModel(
            name='Aeroport',
        ),
        migrations.DeleteModel(
            name='Port',
        ),
    ]
