# Generated by Django 3.1.2 on 2020-11-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villeDepart', models.CharField(help_text='Voyage prix', max_length=20)),
                ('villeArrivee', models.CharField(help_text='Voyage prix', max_length=20)),
                ('dateVoyage', models.DateTimeField(verbose_name='Date de voyage')),
                ('adresseUser', models.EmailField(max_length=255, verbose_name='Adresse de client')),
                ('telephoneUser', models.CharField(max_length=20, verbose_name='Téléphone du client')),
                ('prixVoyage', models.IntegerField(verbose_name='Prix du voyage')),
                ('dateAchat', models.DateTimeField(help_text='Voyage prix', max_length=20)),
            ],
        ),
    ]
