# Generated by Django 3.1.2 on 2020-11-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='dateAchat',
            field=models.DateTimeField(help_text="Date d'achat", max_length=20, verbose_name="Date d'achat"),
        ),
        migrations.AlterField(
            model_name='achat',
            name='villeArrivee',
            field=models.CharField(help_text='Ville de destination', max_length=20, verbose_name='Ville de destination'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='villeDepart',
            field=models.CharField(help_text='Ville de depart', max_length=20, verbose_name='Ville de depart'),
        ),
    ]
