# Generated by Django 3.1.2 on 2020-12-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0002_auto_20201130_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='dateAchat',
            field=models.DateTimeField(auto_now_add=True, help_text="Date d'achat", max_length=20, verbose_name="Date d'achat"),
        ),
    ]
