# Generated by Django 3.1.7 on 2021-03-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0003_auto_20201215_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='dateVoyage',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='prixVoyage',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='villeArrivee',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='villeDepart',
        ),
        migrations.AddField(
            model_name='achat',
            name='agence',
            field=models.CharField(default='Gombessa', max_length=20, verbose_name='Agence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achat',
            name='codeVoyage',
            field=models.CharField(default='KHHGHZUIUZU-KZJ', max_length=20, verbose_name='Code de voyage'),
            preserve_default=False,
        ),
    ]
