# Generated by Django 3.1.7 on 2021-03-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0004_auto_20210309_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='voyagetype',
            field=models.CharField(default='Avion', max_length=20, verbose_name='Type de voyage'),
        ),
    ]
