# Generated by Django 3.1.7 on 2021-03-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0005_achat_voyagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='voyagetype',
            field=models.CharField(max_length=20, verbose_name='Type de voyage'),
        ),
    ]
