# Generated by Django 3.1.2 on 2020-11-30 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agence', '0006_auto_20201128_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gombessa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateVente', models.DateTimeField(auto_now_add=True, verbose_name="Date d'achat")),
                ('montantDeVente', models.IntegerField(verbose_name="Montant de l'achat")),
                ('montantRecu', models.IntegerField(verbose_name="Montant redut sur le montant de l'achat")),
            ],
        ),
        migrations.CreateModel(
            name='BanqueAgencePrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateVente', models.DateTimeField(auto_now_add=True, verbose_name="Date d'achat")),
                ('montantDeVente', models.IntegerField(verbose_name="Montant de l'achat")),
                ('reduction', models.IntegerField(verbose_name="Montant redut sur le montant de l'achat")),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agence', to='agence.agence', verbose_name='Agence')),
            ],
        ),
    ]
