# Generated by Django 3.1.2 on 2020-12-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterÎlesAir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateVente', models.DateTimeField(auto_now_add=True, verbose_name="Date d'achat")),
                ('montantDeVente', models.IntegerField(verbose_name="Montant de l'achat")),
                ('montantRecu', models.IntegerField(verbose_name="Montant redut sur le montant de l'achat")),
            ],
        ),
    ]
