# Generated by Django 3.1.7 on 2021-02-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banques', '0003_auto_20210226_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banque',
            name='reduction',
            field=models.IntegerField(verbose_name='Taux de réduction'),
        ),
    ]
