# Generated by Django 3.1.7 on 2021-02-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banques', '0004_auto_20210226_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banque',
            options={'verbose_name': 'Banque principale'},
        ),
        migrations.AlterField(
            model_name='banque',
            name='reduction',
            field=models.IntegerField(default=20, verbose_name='Taux de réduction'),
        ),
    ]
