# Generated by Django 3.1.2 on 2020-11-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='age',
            field=models.IntegerField(default=20, verbose_name='Age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(default='zaenma@zaenma.fr', max_length=255, verbose_name='Adresse email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(default='zaenma', max_length=30, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(default='Salim', max_length=30, verbose_name='Prénom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(default='267898765', max_length=30, verbose_name='Téléphone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='titre',
            field=models.CharField(choices=[('M', 'Monsieur'), ('F', 'Madame')], default='Mr', max_length=30, verbose_name='Titre'),
            preserve_default=False,
        ),
    ]
