# Generated by Django 3.1.2 on 2020-11-13 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='dateEngregistrement',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 13, 20, 19, 48, 451758, tzinfo=utc), verbose_name='Date inscrit'),
            preserve_default=False,
        ),
    ]
