# Generated by Django 3.1.2 on 2020-11-15 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_utilisateur_dateengregistrement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='nombreEnfants',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='allerRetour',
            field=models.BooleanField(default=False, help_text='Aller Retour', verbose_name='Aller retour'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='dateRetour',
            field=models.DateField(default=datetime.datetime(2020, 11, 15, 9, 26, 44, 820265, tzinfo=utc), help_text='Date de retour du client', verbose_name='Date de retour'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='condition',
            field=models.BooleanField(help_text="Conditions d'utilisation", verbose_name="Condition d'utilisation"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='dateNaissance',
            field=models.DateField(help_text='Date de nissance', max_length=20, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.CharField(help_text='Adresse e-mail', max_length=20, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(help_text='Nom du client', max_length=20, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nombreSiegeReserve',
            field=models.IntegerField(default=1, help_text='Nombre de sièges', verbose_name='Nombre de place à réserver'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(help_text='Prenom du client', max_length=20, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(help_text='Téléphone principale', max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephoneSupplementaire',
            field=models.CharField(blank=True, help_text='Téléphone secondaire', max_length=20, null=True, verbose_name='Autre Téléphone supplémentaire'),
        ),
    ]
