# Generated by Django 3.1.2 on 2020-11-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_auto_20201115_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.CharField(help_text='Adresse e-mail', max_length=100, verbose_name='E-mail'),
        ),
    ]
