# Generated by Django 3.1.2 on 2020-11-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_auto_20201106_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='condition',
            field=models.BooleanField(default=True, verbose_name="Condition d'utilisation"),
        ),
    ]
