# Generated by Django 3.1.2 on 2020-11-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_auto_20201115_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='recevoirAlert',
            field=models.BooleanField(default=False, help_text="Envoie d'alerte", verbose_name='Reception des alertes'),
        ),
    ]
