# Generated by Django 3.1.2 on 2020-11-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_auto_20201124_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='allerRetour',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='dateRetour',
        ),
    ]
