# Generated by Django 3.1.2 on 2020-11-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_auto_20201107_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='created_at',
        ),
    ]
