# Generated by Django 3.1.5 on 2021-01-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_auto_20201128_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du client', max_length=20, verbose_name='Nom')),
                ('prenom', models.CharField(help_text='Prenom du client', max_length=20, verbose_name='Prénom')),
                ('dateNaissance', models.DateField(help_text='Date de nissance', max_length=20, verbose_name='Date de naissance')),
                ('email', models.CharField(help_text='Adresse e-mail', max_length=100, verbose_name='E-mail')),
                ('telephone', models.CharField(help_text='Téléphone principale', max_length=20, verbose_name='Téléphone')),
                ('test', models.CharField(help_text='Téléphone principale', max_length=20, verbose_name='Téléphone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
