# Generated by Django 3.1.2 on 2020-11-07 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_auto_20201107_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsablesagence',
            name='utilisateur_ptr',
        ),
        migrations.AddField(
            model_name='responsablesagence',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='condition',
            field=models.BooleanField(default=True, verbose_name="Condition d'utilisation"),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
            preserve_default=False,
        ),
    ]
