# Generated by Django 3.1.5 on 2021-01-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0007_mensuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnesAnnuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du client', max_length=20, verbose_name='Nom')),
                ('prenom', models.CharField(help_text='Prenom du client', max_length=20, verbose_name='Prénom')),
                ('dateNaissance', models.DateField(help_text='Date de nissance', max_length=20, verbose_name='Date de naissance')),
                ('email', models.CharField(help_text='Adresse e-mail', max_length=100, verbose_name='E-mail')),
                ('telephone', models.CharField(help_text='Téléphone principale', max_length=20, verbose_name='Téléphone')),
                ('nombreVoyageParMois', models.IntegerField(help_text='Nombre de voyags', verbose_name='Nombre de voyages par mois')),
                ('dateAbonnement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'abonnement")),
                ('montantMensuelVerse', models.IntegerField(help_text='Montant par mois', verbose_name='Montant minimum à verser par mois')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbonnesMensuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du client', max_length=20, verbose_name='Nom')),
                ('prenom', models.CharField(help_text='Prenom du client', max_length=20, verbose_name='Prénom')),
                ('dateNaissance', models.DateField(help_text='Date de nissance', max_length=20, verbose_name='Date de naissance')),
                ('email', models.CharField(help_text='Adresse e-mail', max_length=100, verbose_name='E-mail')),
                ('telephone', models.CharField(help_text='Téléphone principale', max_length=20, verbose_name='Téléphone')),
                ('nombreVoyageParMois', models.IntegerField(help_text='Nombre de voyags', verbose_name='Nombre de voyages par mois')),
                ('dateAbonnement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'abonnement")),
                ('montantMensuelVerse', models.IntegerField(help_text='Montant par mois', verbose_name='Montant minimum à verser par mois')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VersementAbonneAnnuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montantMensuelVerse', models.IntegerField(help_text='Montant versé', verbose_name='Montant versé')),
                ('dateVersement', models.DateTimeField(auto_now_add=True, verbose_name='Date de versement')),
                ('abonneMensuel', models.ForeignKey(help_text='Abonné menuel', on_delete=django.db.models.deletion.CASCADE, to='utilisateur.abonnesmensuel', verbose_name='Abonné maensuel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VersementAbonneMensuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montantMensuelVerse', models.IntegerField(help_text='Montant versé', verbose_name='Montant versé')),
                ('dateVersement', models.DateTimeField(auto_now_add=True, verbose_name='Date de versement')),
                ('abonneAnuuel', models.ForeignKey(help_text='Abonné annuel', on_delete=django.db.models.deletion.CASCADE, to='utilisateur.abonnesannuel', verbose_name='Abonné annuel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Mensuel',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='dateEngregistrement',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription"),
        ),
    ]
