# Generated by Django 3.1.2 on 2020-11-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_prevu', '0044_auto_20201107_1314'),
        ('utilisateur', '0008_auto_20201107_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='voyage',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='voyage_prevu.voyagesprevu', verbose_name='Voyage choisi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement"),
        ),
    ]
