# Generated by Django 3.1.7 on 2021-02-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0008_auto_20210113_2202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VersementAbonneMensuel',
            new_name='VersementsAbonneAnnuel',
        ),
        migrations.RenameModel(
            old_name='VersementAbonneAnnuel',
            new_name='VersementsAbonneMensuel',
        ),
        migrations.AlterModelOptions(
            name='abonnesannuel',
            options={'verbose_name': 'Adonnements mensuel'},
        ),
        migrations.AlterModelOptions(
            name='abonnesmensuel',
            options={'verbose_name': 'Abonnements mensuel'},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Les Clients'},
        ),
        migrations.AlterModelOptions(
            name='versementsabonneannuel',
            options={'verbose_name': 'Versement des adonnements annuel'},
        ),
        migrations.AlterModelOptions(
            name='versementsabonnemensuel',
            options={'verbose_name': 'Versement des adonnements mensuel'},
        ),
    ]
