# Generated by Django 3.1.7 on 2021-02-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0009_auto_20210226_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnesannuel',
            name='codeAbonnement',
            field=models.CharField(default='ANDH-1325KHHH00', help_text="Code d'abonnement", max_length=20, unique=True, verbose_name="Code d'abonnement"),
        ),
        migrations.AddField(
            model_name='abonnesmensuel',
            name='codeAbonnement',
            field=models.CharField(default='ANDH-1325KHHH00', help_text="Code d'abonnement", max_length=20, unique=True, verbose_name="Code d'abonnement"),
        ),
        migrations.AlterField(
            model_name='abonnesannuel',
            name='nombreVoyageParMois',
            field=models.IntegerField(blank=True, help_text='Nombre de voyags', null=True, verbose_name='Nombre de voyages par mois'),
        ),
        migrations.AlterField(
            model_name='abonnesmensuel',
            name='nombreVoyageParMois',
            field=models.IntegerField(blank=True, help_text='Nombre de voyags', null=True, verbose_name='Nombre de voyages par mois'),
        ),
    ]
