# Generated by Django 3.1.2 on 2020-11-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0009_auto_20201109_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='voyage',
        ),
    ]
