# Generated by Django 3.1.7 on 2021-02-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0010_auto_20210227_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnesannuel',
            name='codeAbonnement',
            field=models.CharField(help_text="Code d'abonnement", max_length=20, unique=True, verbose_name="Code d'abonnement"),
        ),
        migrations.AlterField(
            model_name='abonnesmensuel',
            name='codeAbonnement',
            field=models.CharField(help_text="Code d'abonnement", max_length=20, unique=True, verbose_name="Code d'abonnement"),
        ),
    ]
