# Generated by Django 3.1.7 on 2021-02-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0011_auto_20210227_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeAbonnement', models.CharField(help_text="Code d'abonnement", max_length=20, unique=True, verbose_name="Code d'abonnement")),
                ('nombrePlace', models.IntegerField(default=1)),
            ],
        ),
    ]
