# Generated by Django 3.1.7 on 2021-03-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0013_abonneshebdomadaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnesannuel',
            name='nombreSiegeReserve',
            field=models.IntegerField(blank=True, help_text='Nombre de voyags', null=True, verbose_name="Nombre de siège pour l'achat"),
        ),
        migrations.AddField(
            model_name='abonneshebdomadaire',
            name='nombreSiegeReserve',
            field=models.IntegerField(blank=True, help_text='Nombre de voyags', null=True, verbose_name="Nombre de siège pour l'achat"),
        ),
        migrations.AddField(
            model_name='abonnesmensuel',
            name='nombreSiegeReserve',
            field=models.IntegerField(blank=True, help_text='Nombre de voyags', null=True, verbose_name="Nombre de siège pour l'achat"),
        ),
    ]
