# Generated by Django 3.1.7 on 2021-03-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0014_auto_20210305_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnesannuel',
            name='nombreSiegeReserve',
            field=models.IntegerField(default=1, help_text='Nombre de voyags', verbose_name="Nombre de siège pour l'achat"),
        ),
        migrations.AlterField(
            model_name='abonneshebdomadaire',
            name='nombreSiegeReserve',
            field=models.IntegerField(default=1, help_text='Nombre de voyags', verbose_name="Nombre de siège pour l'achat"),
        ),
        migrations.AlterField(
            model_name='abonnesmensuel',
            name='nombreSiegeReserve',
            field=models.IntegerField(default=1, help_text='Nombre de voyags', verbose_name="Nombre de siège pour l'achat"),
        ),
    ]
