# Generated by Django 3.1.7 on 2021-03-06 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0015_auto_20210305_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Les Client'},
        ),
    ]
