# Generated by Django 3.1.2 on 2020-11-12 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('ile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyages.ile')),
            ],
        ),
        migrations.CreateModel(
            name='voyagesParBu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencePrincipal', models.CharField(max_length=50, verbose_name='Agence Organisatrice du voyage')),
                ('codeVoyage', models.CharField(max_length=50, verbose_name='Code de voyage (Identifiant du Voyage)')),
                ('dateDepert', models.DateTimeField(verbose_name='Date de départ')),
                ('datearrivee', models.DateTimeField(blank=True, null=True, verbose_name="Date d'arrivée à prevoir")),
                ('dateretour', models.DateTimeField(blank=True, verbose_name="Date d'arrivée à prevoir")),
                ('nombreSiege', models.IntegerField(blank=True, verbose_name='Total de siège disponible')),
                ('prix', models.IntegerField(verbose_name='Prix par siège')),
                ('bagage', models.IntegerField(blank=True, verbose_name='Quantité de bagage autorisé')),
                ('ile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='voyages.ile', verbose_name="Ile : si c'est une voyage terrestre")),
                ('villeArrivee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Ville_desnation', to='voyages.ville', verbose_name='Ville de destination')),
                ('villeDepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyages.ville', verbose_name='Ville de départ')),
                ('villeEscale', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='VilleEcale', to='voyages.ville', verbose_name="Villes d'sscale (si l'on prevoit)")),
            ],
        ),
        migrations.CreateModel(
            name='voyagesParBateau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencePrincipal', models.CharField(max_length=50, verbose_name='Agence Organisatrice du voyage')),
                ('codeVoyage', models.CharField(max_length=50, verbose_name='Code de voyage (Identifiant du Voyage)')),
                ('dateDepert', models.DateTimeField(verbose_name='Date de départ')),
                ('datearrivee', models.DateTimeField(blank=True, null=True, verbose_name="Date d'arrivée à prevoir")),
                ('dateretour', models.DateTimeField(blank=True, verbose_name="Date d'arrivée à prevoir")),
                ('nombreSiege', models.IntegerField(blank=True, verbose_name='Total de siège disponible')),
                ('prix', models.IntegerField(verbose_name='Prix par siège')),
                ('bagage', models.IntegerField(blank=True, verbose_name='Quantité de bagage autorisé')),
                ('ile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='voyages.ile', verbose_name="Ile : si c'est une voyage terrestre")),
                ('villeArrivee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Vle_destination', to='voyages.ville', verbose_name='Ville de destination')),
                ('villeDepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyages.ville', verbose_name='Ville de départ')),
                ('villeEscale', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lleEscale', to='voyages.ville', verbose_name="Villes d'sscale (si l'on prevoit)")),
            ],
        ),
        migrations.CreateModel(
            name='voyagesParAvion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencePrincipal', models.CharField(max_length=50, verbose_name='Agence Organisatrice du voyage')),
                ('codeVoyage', models.CharField(max_length=50, verbose_name='Code de voyage (Identifiant du Voyage)')),
                ('dateDepert', models.DateTimeField(verbose_name='Date de départ')),
                ('datearrivee', models.DateTimeField(blank=True, null=True, verbose_name="Date d'arrivée à prevoir")),
                ('dateretour', models.DateTimeField(blank=True, verbose_name="Date d'arrivée à prevoir")),
                ('nombreSiege', models.IntegerField(blank=True, verbose_name='Total de siège disponible')),
                ('prix', models.IntegerField(verbose_name='Prix par siège')),
                ('bagage', models.IntegerField(blank=True, verbose_name='Quantité de bagage autorisé')),
                ('villeArrivee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Ville_destition', to='voyages.ile', verbose_name='Ville de destination')),
                ('villeDepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyages.ile', verbose_name='Ville de départ')),
                ('villeEscale', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='VilleEscae', to='voyages.ile', verbose_name="Villes d'sscale (si l'on prevoit)")),
            ],
        ),
    ]
