# Generated by Django 3.1.2 on 2020-11-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0002_auto_20201112_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagesparavion',
            name='bagage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantité de bagage autorisé'),
        ),
        migrations.AlterField(
            model_name='voyagesparavion',
            name='dateRetour',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de retour'),
        ),
        migrations.AlterField(
            model_name='voyagesparbateau',
            name='bagage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantité de bagage autorisé'),
        ),
        migrations.AlterField(
            model_name='voyagesparbu',
            name='bagage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantité de bagage autorisé'),
        ),
        migrations.AlterField(
            model_name='voyagesparbu',
            name='dateRetour',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de retour pour ce vol'),
        ),
        migrations.AlterField(
            model_name='voyagesparbu',
            name='nombreSiege',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total de siège disponible'),
        ),
    ]
