# Generated by Django 3.1.2 on 2020-11-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0003_auto_20201112_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagesparavion',
            name='nombreSiege',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total de siège disponible'),
        ),
    ]
