# Generated by Django 3.1.2 on 2020-11-12 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0004_auto_20201112_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagesparavion',
            name='villeEscale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='VilleEscae', to='voyages.ile', verbose_name="Villes d'sscale (si l'on prevoit)"),
        ),
        migrations.AlterField(
            model_name='voyagesparbateau',
            name='villeEscale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lleEscale', to='voyages.ville', verbose_name="Villes d'sscale (si l'on prevoit)"),
        ),
        migrations.AlterField(
            model_name='voyagesparbu',
            name='villeEscale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='VilleEcale', to='voyages.ville', verbose_name="Villes d'sscale (si l'on prevoit)"),
        ),
    ]
