# Generated by Django 3.1.2 on 2020-11-12 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0005_auto_20201112_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typev', models.CharField(max_length=50)),
                ('date_depart', models.DateTimeField()),
                ('date_retour', models.DateTimeField(blank=True)),
                ('ile', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='voyages.ile')),
                ('ville_depart', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='voyages.ville')),
                ('ville_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vile_destination', to='voyages.ville')),
            ],
        ),
        migrations.CreateModel(
            name='ModelBateau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typev', models.CharField(max_length=50)),
                ('date_depart', models.DateTimeField()),
                ('date_retour', models.DateTimeField(blank=True)),
                ('ville_depart', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='Vile_destinaion', to='voyages.ile')),
                ('ville_destination', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='Vile_destinatin', to='voyages.ile')),
            ],
        ),
        migrations.CreateModel(
            name='ModelAvion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typev', models.CharField(max_length=50)),
                ('date_depart', models.DateTimeField()),
                ('date_retour', models.DateTimeField(blank=True)),
                ('ville_depart', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='Vile_desnation', to='voyages.ile')),
                ('ville_destination', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='Vile_dstination', to='voyages.ile')),
            ],
        ),
    ]
