# Generated by Django 3.1.2 on 2020-11-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0006_modelavion_modelbateau_modelbus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyagesparbateau',
            name='ile',
        ),
        migrations.RemoveField(
            model_name='voyagesparbu',
            name='dateRetour',
        ),
        migrations.AlterField(
            model_name='modelavion',
            name='date_retour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelbateau',
            name='date_retour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelbus',
            name='date_retour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voyagesparavion',
            name='agencePrincipal',
            field=models.CharField(max_length=50, verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='voyagesparavion',
            name='dateArrivee',
            field=models.DateTimeField(verbose_name="Date d'arrivée à prevoir"),
        ),
        migrations.AlterField(
            model_name='voyagesparavion',
            name='dateDepert',
            field=models.DateTimeField(verbose_name='Date de depart'),
        ),
        migrations.AlterField(
            model_name='voyagesparavion',
            name='nombreSiege',
            field=models.IntegerField(verbose_name='Total de siège disponible'),
        ),
        migrations.AlterField(
            model_name='voyagesparavion',
            name='villeDepart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyages.ile', verbose_name='Ville de depart'),
        ),
        migrations.AlterField(
            model_name='voyagesparbateau',
            name='agencePrincipal',
            field=models.CharField(max_length=50, verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='voyagesparbateau',
            name='dateArrivee',
            field=models.DateTimeField(verbose_name="Date d'arrivée à prevoir"),
        ),
        migrations.AlterField(
            model_name='voyagesparbateau',
            name='dateDepert',
            field=models.DateTimeField(verbose_name='Date de depart'),
        ),
        migrations.AlterField(
            model_name='voyagesparbateau',
            name='nombreSiege',
            field=models.IntegerField(verbose_name='Total de siège disponible'),
        ),
        migrations.AlterField(
            model_name='voyagesparbateau',
            name='villeDepart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyages.ville', verbose_name='Ville de depart'),
        ),
        migrations.AlterField(
            model_name='voyagesparbateau',
            name='villeEscale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lleEscale', to='voyages.ile', verbose_name="Villes d'sscale (si l'on prevoit)"),
        ),
        migrations.AlterField(
            model_name='voyagesparbu',
            name='agencePrincipal',
            field=models.CharField(max_length=50, verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='voyagesparbu',
            name='bagage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantité de bagages autorisées'),
        ),
        migrations.AlterField(
            model_name='voyagesparbu',
            name='ile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyages.ile', verbose_name='Ile : un voyage terrestre'),
        ),
        migrations.AlterField(
            model_name='voyagesparbu',
            name='nombreSiege',
            field=models.IntegerField(verbose_name='Total de sièges disponible'),
        ),
    ]
