# Generated by Django 3.1.2 on 2020-11-13 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0010_auto_20201113_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagesparbateau',
            name='villeArrivee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Vle_destination', to='voyages.ile', verbose_name='Ville de destination'),
        ),
        migrations.AlterField(
            model_name='voyagesparbateau',
            name='villeDepart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyages.ile', verbose_name='Ville de depart'),
        ),
    ]
