# Generated by Django 3.1.2 on 2020-11-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0011_auto_20201113_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='ile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyages.ile', verbose_name="île d'où elle se situe"),
        ),
        migrations.AlterField(
            model_name='ville',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Nom de la ville'),
        ),
    ]
