# Generated by Django 3.1.7 on 2021-02-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0015_auto_20201128_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ile',
            options={'verbose_name': 'Les île'},
        ),
        migrations.AlterModelOptions(
            name='ville',
            options={'verbose_name': 'Les ville'},
        ),
        migrations.AlterModelOptions(
            name='voyagesparavion',
            options={'verbose_name': 'Les voyages aérien'},
        ),
        migrations.AlterModelOptions(
            name='voyagesparbateau',
            options={'verbose_name': 'Les voyages maritime'},
        ),
        migrations.AlterModelOptions(
            name='voyagesparbu',
            options={'verbose_name': 'Les voyages terrestres'},
        ),
    ]
