# Generated by Django 3.1.2 on 2020-11-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voyages', '0012_auto_20201124_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAgence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=255, verbose_name="Adresse email de l'expediteur")),
                ('destinateur', models.EmailField(max_length=255, verbose_name='Adresse email du destinateur')),
                ('telephone', models.CharField(max_length=100, verbose_name="Téléphone de l'expediteur")),
                ('sujet', models.CharField(max_length=255, verbose_name='Titre du message')),
                ('message', models.TextField(verbose_name='Messages')),
                ('dateEnvoie', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoie")),
            ],
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('telephoneFixe', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone Fixe')),
                ('telephonePortable', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone portable')),
                ('adresseEmail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse email')),
                ('codepostal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code postal')),
                ('typeAgence', models.CharField(max_length=50, verbose_name="Type de l'agence")),
                ('description', models.TextField(verbose_name="Description de l'agence")),
                ('responsable', models.CharField(max_length=50)),
                ('dateAjout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'integration")),
                ('ileLocalisation', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='voyages.ile', verbose_name='Île de localisation')),
                ('villeLocalisation', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='voyages.ville', verbose_name='Ville de localisation')),
            ],
        ),
    ]
