# Generated by Django 3.1.2 on 2020-11-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='dateModifiee',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='telephonePortable',
            field=models.CharField(max_length=50, verbose_name='Téléphone portable'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='typeAgence',
            field=models.CharField(choices=[('AV', 'Avion'), ('AV', 'Avion'), ('AV', 'Avion')], max_length=50, verbose_name="Type de l'agence"),
        ),
    ]
