# Generated by Django 3.1.2 on 2020-11-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0002_auto_20201128_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='typeAgence',
            field=models.CharField(choices=[('AV', 'Avion'), ('BA', 'Bateau'), ('BU', 'Bus')], max_length=50, verbose_name="Type de l'agence"),
        ),
    ]
