# Generated by Django 3.1.2 on 2020-11-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0002_auto_20201104_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='agence',
            name='email',
            field=models.EmailField(max_length=254, verbose_name="Adresse email de 'agence"),
        ),
        migrations.AlterField(
            model_name='agence',
            name='nom',
            field=models.CharField(max_length=50, verbose_name="Nom de l'agence"),
        ),
        migrations.AlterField(
            model_name='agence',
            name='telephone',
            field=models.CharField(max_length=50, verbose_name="Téléphone de l'agence"),
        ),
        migrations.AlterField(
            model_name='typeagence',
            name='nom',
            field=models.CharField(choices=[('BATEAU', 'Agence de voyage maritime'), ('AVION', 'Agence de voyage aérièn'), ('BUS', 'Agence de voyage terrestre')], max_length=50, verbose_name="Type d'agence"),
        ),
    ]
