# Generated by Django 3.1.2 on 2020-11-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0003_auto_20201104_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='typeAgence',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='agence.typeagence', verbose_name="Type d'agence"),
        ),
        migrations.AlterField(
            model_name='typeagence',
            name='nom',
            field=models.CharField(choices=[('Agence de voyage maritime', 'Agence de voyage maritime'), ('Agence de voyage aérièn', 'Agence de voyage aérièn'), ('Agence de voyage terrestre', 'Agence de voyage terrestre')], max_length=50, verbose_name="Type d'agence"),
        ),
    ]
