# Generated by Django 3.1.2 on 2020-11-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0005_auto_20201104_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='typeAgence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agence.typeagence', verbose_name="Type d'agence"),
        ),
        migrations.AlterField(
            model_name='typeagence',
            name='nom',
            field=models.CharField(choices=[('Bateau', 'Agence de voyage maritime'), ('Avion', 'Agence de voyage aérien'), ('bus', 'Agence de voyage terrestre')], max_length=50, verbose_name="Type d'agence"),
        ),
    ]
