# Generated by Django 3.1.2 on 2020-11-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0005_auto_20201128_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='telephonePortable',
            field=models.CharField(default=34567890, max_length=50, verbose_name='Téléphone portable'),
            preserve_default=False,
        ),
    ]
