# Generated by Django 3.1.2 on 2020-12-16 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0006_auto_20201128_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinateur', models.EmailField(max_length=255, verbose_name='Adresse email du destinateur')),
                ('reponse', models.TextField(verbose_name='Messages')),
                ('dateEnvoie', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoie")),
                ('sujet', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='agence.messageagence', verbose_name='Titre du message')),
            ],
        ),
    ]
