# Generated by Django 3.1.7 on 2021-03-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0007_reponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='password',
            field=models.CharField(default='Zaenma-29', max_length=20, unique=True),
        ),
    ]
