# Generated by Django 3.1.7 on 2021-03-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0011_auto_20210301_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='password',
        ),
    ]
