# Generated by Django 3.1.7 on 2021-03-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0012_remove_agence_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='mdp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
