# Generated by Django 3.1.7 on 2021-03-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0015_auto_20210303_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageagence',
            options={'verbose_name': 'Messages reçu'},
        ),
        migrations.AlterModelOptions(
            name='reponse',
            options={'verbose_name': 'Réponses envoyé'},
        ),
        migrations.RemoveField(
            model_name='messageagence',
            name='destinateur',
        ),
        migrations.RemoveField(
            model_name='messageagence',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='messageagence',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name="Adresse email de l'expediteur"),
        ),
        migrations.AlterField(
            model_name='messageagence',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Téléphone de l'expediteur"),
        ),
    ]
