# Generated by Django 3.1.7 on 2021-03-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0017_messagesenvoye'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageagence',
            name='agence',
            field=models.CharField(default='AB Aviation', max_length=50, verbose_name='Agence destinataire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagesenvoye',
            name='agence',
            field=models.EmailField(default='AB Aviation', max_length=50, verbose_name='Agence expédiée'),
        ),
        migrations.AlterField(
            model_name='messageagence',
            name='nom',
            field=models.CharField(max_length=50, verbose_name="Nom de l'expéditeur"),
        ),
        migrations.AlterField(
            model_name='messagesenvoye',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email du destinataire'),
        ),
    ]
